#index:
#    path: /
#    controller: App\Controller\DefaultController::index


security_registration:
  path:     /register
  defaults: { _controller: App\Controller\SecurityController::registration }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }


security_redirectuser:
  path:     /redirectuser
  defaults: { _controller: App\Controller\SecurityController::redirectuser }


security_updpwd:
  path:     /updatepasswd/{id}
  defaults: { _controller: App\Controller\SecurityController::updatepwd }



security_resetpwd:
  path:     /resetpasswd
  defaults: { _controller: App\Controller\SecurityController::resetpwd }


security_resetting:
  path:     /resetting/{id}/{token}
  defaults: { _controller: App\Controller\SecurityController::resetting }


security_updprofil:
  path:     /updateprofil/{id}
  defaults: { _controller: App\Controller\SecurityController::updateprofil }


siges_dashboardteacher:
  path:     /teacherarea/dashboardteacher
  defaults: { _controller: App\Controller\TeacherController::dashboardteacher }





siges_averagedashteacher:
  path:     /teacherarea/averagedashteacher
  defaults: { _controller: App\Controller\TeacherController::averagedashteacher }


siges_teachereculist:
  path:     /teacherarea/teachereculist
  defaults: { _controller: App\Controller\TeacherController::teachereculist }


siges_eculist:
  path:     /teacherarea/eculist
  defaults: { _controller: App\Controller\TeacherController::eculist }

siges_alertvalidation:
  path:     /teacherarea/alertvalidation
  defaults: { _controller: App\Controller\TeacherController::alertvalidation}


siges_alertdeadlinesaisie:
  path:     /teacherarea/alertdeadlinesaisie
  defaults: { _controller: App\Controller\TeacherController::alertdeadlinesaisie}



siges_redirectentryaverages:
  path:     /teacherarea/redirectentryaverages
  defaults: { _controller: App\Controller\TeacherController::redirectentryaverages}



siges_entryaverages:
  path:     /teacherarea/entryaverages
  defaults: { _controller: App\Controller\TeacherController::entryaverages }




siges_teachereculistvalidation:
  path:     /teacherarea/teachereculistvalidation
  defaults: { _controller: App\Controller\TeacherController::teachereculistvalidation }


siges_eculistvalidation:
  path:     /teacherarea/eculistvalidation
  defaults: { _controller: App\Controller\TeacherController::eculistvalidation }



siges_alertdeadlinevalid:
  path:     /teacherarea/alertdeadlinevalid
  defaults: { _controller: App\Controller\TeacherController::alertdeadlinevalid}



siges_redirectvalidaverages:
  path:     /teacherarea/redirectvalidaverages
  defaults: { _controller: App\Controller\TeacherController::redirectvalidaverages}







siges_validaveragesedit:
  path:     /teacherarea/validaveragesedit
  defaults: { _controller: App\Controller\TeacherController::validaveragesedit }




siges_validallaverages:
  path:     /teacherarea/validallaverages
  defaults: { _controller: App\Controller\TeacherController::validallaverages }



siges_unvalidallaverages:
  path:     /teacherarea/unvalidallaverages
  defaults: { _controller: App\Controller\TeacherController::unvalidallaverages }



siges_savevalidallaverages:
  path:     /teacherarea/savevalidallaverages
  defaults: { _controller: App\Controller\TeacherController::savevalidallaverages }


siges_saveunvalidallaverages:
  path:     /teacherarea/saveunvalidallaverages
  defaults: { _controller: App\Controller\TeacherController::saveunvalidallaverages }


siges_dashboardpedagores:
  path:     /pedagoresarea/dashboardpedagores
  defaults: { _controller: App\Controller\PedagoResController::dashboardpedagores }

siges_averagedashpedagores:
  path:     /pedagoresarea/averagedashpedagores
  defaults: { _controller: App\Controller\PedagoResController::averagedashpedagores }



siges_redirectspecsemnex:
  path:     /pedagoresarea/redirectspecsemnex
  defaults: { _controller: App\Controller\PedagoResController::redirectspecsemnex }

siges_specsemnex:
  path:     /pedagoresarea/specsemnex
  defaults: { _controller: App\Controller\PedagoResController::specsemnex }


siges_listspecsemnex:
  path:     /pedagoresarea/listspecsemnex
  defaults: { _controller: App\Controller\PedagoResController::listspecsemnex }




siges_redirectecusemnex:
  path:     /pedagoresarea/redirectecusemnex
  defaults: { _controller: App\Controller\PedagoResController::redirectecusemnex }

siges_ecusemnex:
  path:     /pedagoresarea/ecusemnex
  defaults: { _controller: App\Controller\PedagoResController::ecusemnex }


siges_listecusemnex:
  path:     /pedagoresarea/listecusemnex
  defaults: { _controller: App\Controller\PedagoResController::listecusemnex }





siges_redirectentrynotexam:
  path:     /pedagoresarea/redirectentrynotexam
  defaults: { _controller: App\Controller\PedagoResController::redirectentrynotexam }





siges_entrynotexam:
  path:     /pedagoresarea/entrynotexam
  defaults: { _controller: App\Controller\PedagoResController::entrynotexam }



siges_oversightdashpedagores:
  path:     /pedagoresarea/oversightdashpedagores
  defaults: { _controller: App\Controller\PedagoResController::oversightdashpedagores }


siges_redirectoversightrp:
  path:     /pedagoresarea/redirectoversightrp
  defaults: { _controller: App\Controller\PedagoResController::redirectoversightrp }


siges_oversightrp:
  path:     /pedagoresarea/oversightrp
  defaults: { _controller: App\Controller\PedagoResController::oversightrp }
