#index:
#    path: /
#    controller: App\Controller\DefaultController::index


security_registration:
  path:     /register
  defaults: { _controller: App\Controller\SecurityController::registration }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }


security_redirectuser:
  path:     /redirectuser
  defaults: { _controller: App\Controller\SecurityController::redirectuser }


security_updpwd:
  path:     /updatepasswd/{id}
  defaults: { _controller: App\Controller\SecurityController::updatepwd }



security_resetpwd:
  path:     /resetpasswd
  defaults: { _controller: App\Controller\SecurityController::resetpwd }


security_resetting:
  path:     /resetting/{id}/{token}
  defaults: { _controller: App\Controller\SecurityController::resetting }


security_updprofil:
  path:     /updateprofil/{id}
  defaults: { _controller: App\Controller\SecurityController::updateprofil }


siges_dashboardteacher:
  path:     /teacherarea/dashboardteacher
  defaults: { _controller: App\Controller\TeacherController::dashboardteacher }





siges_averagedashteacher:
  path:     /teacherarea/averagedashteacher
  defaults: { _controller: App\Controller\TeacherController::averagedashteacher }


siges_teachereculist:
  path:     /teacherarea/teachereculist
  defaults: { _controller: App\Controller\TeacherController::teachereculist }


siges_eculist:
  path:     /teacherarea/eculist
  defaults: { _controller: App\Controller\TeacherController::eculist }

siges_alertvalidation:
  path:     /teacherarea/alertvalidation
  defaults: { _controller: App\Controller\TeacherController::alertvalidation}


siges_alertdeadlinesaisie:
  path:     /teacherarea/alertdeadlinesaisie
  defaults: { _controller: App\Controller\TeacherController::alertdeadlinesaisie}



siges_redirectentryaverages:
  path:     /teacherarea/redirectentryaverages
  defaults: { _controller: App\Controller\TeacherController::redirectentryaverages}



siges_entryaverages:
  path:     /teacherarea/entryaverages
  defaults: { _controller: App\Controller\TeacherController::entryaverages }




siges_teachereculistvalidation:
  path:     /teacherarea/teachereculistvalidation
  defaults: { _controller: App\Controller\TeacherController::teachereculistvalidation }


siges_eculistvalidation:
  path:     /teacherarea/eculistvalidation
  defaults: { _controller: App\Controller\TeacherController::eculistvalidation }



siges_alertdeadlinevalid:
  path:     /teacherarea/alertdeadlinevalid
  defaults: { _controller: App\Controller\TeacherController::alertdeadlinevalid}



siges_redirectvalidaverages:
  path:     /teacherarea/redirectvalidaverages
  defaults: { _controller: App\Controller\TeacherController::redirectvalidaverages}







siges_validaveragesedit:
  path:     /teacherarea/validaveragesedit
  defaults: { _controller: App\Controller\TeacherController::validaveragesedit }




siges_validallaverages:
  path:     /teacherarea/validallaverages
  defaults: { _controller: App\Controller\TeacherController::validallaverages }



siges_unvalidallaverages:
  path:     /teacherarea/unvalidallaverages
  defaults: { _controller: App\Controller\TeacherController::unvalidallaverages }



siges_savevalidallaverages:
  path:     /teacherarea/savevalidallaverages
  defaults: { _controller: App\Controller\TeacherController::savevalidallaverages }


siges_saveunvalidallaverages:
  path:     /teacherarea/saveunvalidallaverages
  defaults: { _controller: App\Controller\TeacherController::saveunvalidallaverages }


siges_dashboardpedagores:
  path:     /pedagoresarea/dashboardpedagores
  defaults: { _controller: App\Controller\PedagoResController::dashboardpedagores }

siges_averagedashpedagores:
  path:     /pedagoresarea/averagedashpedagores
  defaults: { _controller: App\Controller\PedagoResController::averagedashpedagores }



siges_redirectspecsemnex:
  path:     /pedagoresarea/redirectspecsemnex
  defaults: { _controller: App\Controller\PedagoResController::redirectspecsemnex }

siges_specsemnex:
  path:     /pedagoresarea/specsemnex
  defaults: { _controller: App\Controller\PedagoResController::specsemnex }


siges_listspecsemnex:
  path:     /pedagoresarea/listspecsemnex
  defaults: { _controller: App\Controller\PedagoResController::listspecsemnex }




siges_redirectecusemnex:
  path:     /pedagoresarea/redirectecusemnex
  defaults: { _controller: App\Controller\PedagoResController::redirectecusemnex }

siges_ecusemnex:
  path:     /pedagoresarea/ecusemnex
  defaults: { _controller: App\Controller\PedagoResController::ecusemnex }


siges_listecusemnex:
  path:     /pedagoresarea/listecusemnex
  defaults: { _controller: App\Controller\PedagoResController::listecusemnex }





siges_redirectentrynotexam:
  path:     /pedagoresarea/redirectentrynotexam
  defaults: { _controller: App\Controller\PedagoResController::redirectentrynotexam }





siges_entrynotexam:
  path:     /pedagoresarea/entrynotexam
  defaults: { _controller: App\Controller\PedagoResController::entrynotexam }



siges_oversightdashpedagores:
  path:     /oversightdashpedagores
  defaults: { _controller: App\Controller\PedagoResController::oversightdashpedagores }


siges_redirectoversightrp:
  path:     /redirectoversightrp
  defaults: { _controller: App\Controller\PedagoResController::redirectoversightrp }


siges_oversightrp:
  path:     /oversightrp
  defaults: { _controller: App\Controller\PedagoResController::oversightrp }

siges_listaverrp:
  path:     /listaverrp
  defaults: { _controller: App\Controller\PedagoResController::listaverrp }


siges_listnexrp:
  path:     /listnexrp
  defaults: { _controller: App\Controller\PedagoResController::listnexrp }





siges_specmccoversight:
  path:     /specmccoversight
  defaults: { _controller: App\Controller\PedagoResController::specmccoversight }



siges_listspecmccoversight:
  path:     /listspecmccoversight
  defaults: { _controller: App\Controller\PedagoResController::listspecmccoversight}





siges_redirectecumccover:
  path:     /redirectecumccover
  defaults: { _controller: App\Controller\PedagoResController::redirectecumccover }




siges_ecumccoversight:
  path:     /ecumccoversight
  defaults: { _controller: App\Controller\PedagoResController::ecumccoversight }



siges_listecumccoversight:
  path:     /listecumccoversight
  defaults: { _controller: App\Controller\PedagoResController::listecumccoversight}







siges_specnexoversight:
  path:     /specnexoversight
  defaults: { _controller: App\Controller\PedagoResController::specnexoversight }



siges_listspecnexoversight:
  path:     /listspecnexoversight
  defaults: { _controller: App\Controller\PedagoResController::listspecnexoversight}





siges_redirectecunexover:
  path:     /redirectecunexover
  defaults: { _controller: App\Controller\PedagoResController::redirectecunexover }




siges_ecunexoversight:
  path:     /ecunexoversight
  defaults: { _controller: App\Controller\PedagoResController::ecunexoversight }



siges_listecunexoversight:
  path:     /listecunexoversight
  defaults: { _controller: App\Controller\PedagoResController::listecunexoversight}



siges_dashboardsupdp:
  path:     /dparea/dashboardsupdp
  defaults: { _controller: App\Controller\DpController::dashboardsupdp }

siges_choiceacadyear:
  path:     /delibarea/choiceacadyear
  defaults: { _controller: App\Controller\DelibSemController::choiceacadyear }

siges_dashboarddelib:
  path:     /delibarea/dashboarddelib
  defaults: { _controller: App\Controller\DelibSemController::dashboarddelib }

siges_redirectdelibspecbylevel:
  path:     /delibarea/redirectdelibspecbylevel
  defaults: { _controller: App\Controller\DelibSemController::redirectdelibspecbylevel }

siges_delibspecbylevel:
  path:     /delibarea/delibspecbylevel/{idses}/{semtype}
  defaults: { _controller: App\Controller\DelibSemController::delibspecbylevel }

siges_listdelibspecbylevel:
  path:     /delibarea/listdelibspecbylevel
  defaults: { _controller: App\Controller\DelibSemController::listdelibspecbylevel }


siges_redirectdelibbylevel:
  path:     /delibarea/redirectdelibbylevel
  defaults: { _controller: App\Controller\DelibSemController::redirectdelibbylevel }



siges_dashboarddelibbylevel:
  path:     /delibarea/dashboarddelibbylevel
  defaults: { _controller: App\Controller\DelibSemController::dashboarddelibbylevel }

siges_deleteavernull:
  path:     /delibarea/deleteavernull
  defaults: { _controller: App\Controller\DelibSemController::deleteavernull}


siges_savedeleteavernull:
  path:     /delibarea/savedeleteavernull
  defaults: { _controller: App\Controller\DelibSemController::savedeleteavernull}



siges_viewaverzero:
  path:     /delibarea/viewaverzero
  defaults: { _controller: App\Controller\DelibSemController::viewaverzero }

siges_listviewaverzero:
  path:     /delibarea/listviewaverzero
  defaults: { _controller: App\Controller\DelibSemController::listviewaverzero }




siges_viewnotexamzero:
  path:     /delibarea/viewnotexamzero
  defaults: { _controller: App\Controller\DelibSemController::viewnotexamzero }

siges_listviewnotexamzero:
  path:     /delibarea/listviewnotexamzero
  defaults: { _controller: App\Controller\DelibSemController::listviewnotexamzero }


siges_consultaveragedelib:
  path:     /delibarea/consultaveragedelib
  defaults: { _controller: App\Controller\DelibSemController::consultaveragedelib}

siges_listconsultaveragedelib:
  path:     /delibarea/listconsultaveragedelib
  defaults: { _controller: App\Controller\DelibSemController::listconsultaveragedelib }


siges_viewaveragesem:
  path:     /delibarea/viewaveragesem
  defaults: { _controller: App\Controller\DelibSemController::viewaveragesem}

siges_listviewaveragesem:
  path:     /delibarea/listviewaveragesem
  defaults: { _controller: App\Controller\DelibSemController::listviewaveragesem }





siges_viewaveragesemmaster:
  path:     /delibarea/viewaveragesemmaster
  defaults: { _controller: App\Controller\DelibSemController::viewaveragesemmaster}

siges_listviewaveragesemmaster:
  path:     /delibarea/listviewaveragesemmaster
  defaults: { _controller: App\Controller\DelibSemController::listviewaveragesemmaster }






siges_startdelibmaster:
  path:     /delibarea/startdelibmaster
  defaults: { _controller: App\Controller\DelibSemController::startdelibmaster }



siges_startdeliblicence:
  path:     /delibarea/startdeliblicence
  defaults: { _controller: App\Controller\DelibSemController::startdeliblicence }



siges_decisionjury:
  path:     /delibarea/decisionjury
  defaults: { _controller: App\Controller\DelibSemController::decisionjury }



siges_delibannuel:
  path:     /delibarea/delibannuel
  defaults: { _controller: App\Controller\DelibSemController::delibannuel }

siges_startdelib2:
  path:     /delibarea/startdelib2
  defaults: { _controller: App\Controller\DelibSemController::startdelib2 }


siges_stusemvalide:
  path:     /delibarea/stusemvalide
  defaults: { _controller: App\Controller\DelibSemController::stusemvalide }




siges_liststusemvalide:
  path:     /delibarea/liststusemvalide
  defaults: { _controller: App\Controller\DelibSemController::liststusemvalide }



siges_deliberationsemestre:
  path:     /delibarea/deliberationsemestre
  defaults: { _controller: App\Controller\DelibSemController::deliberationsemestre }


siges_deliberationsemestremaster:
  path:     /delibarea/deliberationsemestremaster
  defaults: { _controller: App\Controller\DelibSemController::deliberationsemestremaster }



siges_tabledelibrtell2sem3:
  path:     /delibarea/tabledelibrtell2sem3
  defaults: { _controller: App\Controller\DelibSemController::tabledelibrtell2sem3 }



siges_listtabledelibrtell2sem3:
  path:     /delibarea/listtabledelibrtell2sem3
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibrtell2sem3 }



siges_averclassue:
  path:     /delibarea/averclassue
  defaults: { _controller: App\Controller\DelibSemController::averclassue }



siges_listaverclassue:
  path:     /delibarea/listaverclassue
  defaults: { _controller: App\Controller\DelibSemController::listaverclassue }




siges_enddelib:
  path:     /delibarea/enddelib
  defaults: { _controller: App\Controller\DelibSemController::enddelib }





siges_liststattranche:
  path:     /delibarea/liststattranche
  defaults: { _controller: App\Controller\DelibSemController::liststattranche }



siges_liststatdecision:
  path:     /delibarea/liststatdecision
  defaults: { _controller: App\Controller\DelibSemController::liststatdecision }




siges_liststatpercentadan:
  path:     /delibarea/liststatpercentadan
  defaults: { _controller: App\Controller\DelibSemController::liststatpercentadan }



siges_deliberationsemestreuniq:
  path:     /delibarea/deliberationsemestreuniq
  defaults: { _controller: App\Controller\DelibSemController::deliberationsemestreuniq }




siges_deliberationsemestreuniqmaster:
  path:     /delibarea/deliberationsemestreuniqmaster
  defaults: { _controller: App\Controller\DelibSemController::deliberationsemestreuniqmaster }


siges_consultationecu:
  path:     /delibarea/consultationecu
  defaults: { _controller: App\Controller\DelibSemController::consultationecu }





siges_listconsultationecu:
  path:     /delibarea/listconsultationecu
  defaults: { _controller: App\Controller\DelibSemController::listconsultationecu }





siges_redirectaverageccedituniq:
  path:     /delibarea/redirectaverageccedituniq
  defaults: { _controller: App\Controller\DelibSemController::redirectaverageccedituniq }




siges_edituniqaveragecc:
  path:     /delibarea/edituniqaveragecc
  defaults: { _controller: App\Controller\DelibSemController::edituniqaveragecc }



siges_redirectnotexamedituniq:
  path:     /delibarea/redirectnotexamedituniq
  defaults: { _controller: App\Controller\DelibSemController::redirectnotexamedituniq }




siges_edituniqnotexam:
  path:     /delibarea/edituniqnotexam
  defaults: { _controller: App\Controller\DelibSemController::edituniqnotexam }




siges_tabledecisionjury:
  path:     /delibarea/tabledecisionjury
  defaults: { _controller: App\Controller\DelibSemController::tabledecisionjury }


siges_tabledelibannuel:
  path:     /delibarea/tabledelibannuel
  defaults: { _controller: App\Controller\DelibSemController::tabledelibannuel }



siges_resultannuel:
  path:     /delibarea/resultannuel
  defaults: { _controller: App\Controller\DelibSemController::resultannuel }




siges_tableresultannuel:
  path:     /delibarea/tableresultannuel
  defaults: { _controller: App\Controller\DelibSemController::tableresultannuel }



siges_startorientation:
  path:     /delibarea/startorientation
  defaults: { _controller: App\Controller\DelibSemController::startorientation }



siges_tabledelibm1infosem7:
  path:     /delibarea/tabledelibm1infosem7
  defaults: { _controller: App\Controller\DelibSemController::tabledelibm1infosem7 }




siges_listtabledelibm1infosem7:
  path:     /delibarea/listtabledelibm1infosem7
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibm1infosem7 }




siges_tabledelibmdsim1sem8:
  path:     /delibarea/tabledelibmdsim1sem8
  defaults: { _controller: App\Controller\DelibSemController::tabledelibmdsim1sem8 }




siges_listtabledelibmdsim1sem8:
  path:     /delibarea/listtabledelibmdsim1sem8
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibmdsim1sem8 }






siges_tabledelibm1mdsisem7:
  path:     /delibarea/tabledelibm1mdsisem7
  defaults: { _controller: App\Controller\DelibSemController::tabledelibm1mdsisem7 }




siges_listtabledelibm1mdsisem7:
  path:     /delibarea/listtabledelibm1mdsisem7
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibm1mdsisem7 }





siges_tabledelibsritl3sem5:
  path:     /delibarea/tabledelibsritl3sem5
  defaults: { _controller: App\Controller\DelibSemController::tabledelibsritl3sem5 }




siges_listtabledelibsritl3sem5:
  path:     /delibarea/listtabledelibsritl3sem5
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibsritl3sem5 }






siges_tabledelibrtell3sem5:
  path:     /delibarea/tabledelibrtell3sem5
  defaults: { _controller: App\Controller\DelibSemController::tabledelibrtell3sem5 }




siges_listtabledelibrtell3sem5:
  path:     /delibarea/listtabledelibrtell3sem5
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibrtell3sem5 }





siges_tabledelibsigll3sem5:
  path:     /delibarea/tabledelibsigll3sem5
  defaults: { _controller: App\Controller\DelibSemController::tabledelibsigll3sem5 }




siges_listtabledelibsigll3sem5:
  path:     /delibarea/listtabledelibsigll3sem5
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibsigll3sem5 }





siges_tabledelibtwinl3sem5:
  path:     /delibarea/tabledelibtwinl3sem5
  defaults: { _controller: App\Controller\DelibSemController::tabledelibtwinl3sem5 }




siges_listtabledelibtwinl3sem5:
  path:     /delibarea/listtabledelibtwinl3sem5
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibtwinl3sem5 }


siges_tabledelibm1rtelsem7:
  path:     /delibarea/tabledelibm1rtelsem7
  defaults: { _controller: App\Controller\DelibSemController::tabledelibm1rtelsem7 }




siges_listtabledelibm1rtelsem7:
  path:     /delibarea/listtabledelibm1rtelsem7
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibm1rtelsem7 }


siges_tabledelibm2sitwsem9:
  path:     /delibarea/tabledelibm2sitwsem9
  defaults: { _controller: App\Controller\DelibSemController::tabledelibm2sitwsem9 }




siges_listtabledelibm2sitwsem9:
  path:     /delibarea/listtabledelibm2sitwsem9
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibm2sitwsem9 }





siges_tabledelibm2siglsem9:
  path:     /delibarea/tabledelibm2siglsem9
  defaults: { _controller: App\Controller\DelibSemController::tabledelibm2siglsem9 }




siges_listtabledelibm2siglsem9:
  path:     /delibarea/listtabledelibm2siglsem9
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibm2siglsem9 }



siges_tabledelibm2siglsem9adm:
  path:     /delibarea/tabledelibm2siglsem9adm
  defaults: { _controller: App\Controller\DelibSemController::tabledelibm2siglsem9adm }

siges_listtabledelibm2siglsem9adm:
  path:     /delibarea/listtabledelibm2siglsem9adm
  defaults: { _controller: App\Controller\DelibSemController::listtabledelibm2siglsem9adm }










