#index:
#    path: /
#    controller: App\Controller\DefaultController::index


security_registration:
  path:     /register
  defaults: { _controller: App\Controller\SecurityController::registration }

security_login:
  path:     /login
  defaults: { _controller: App\Controller\SecurityController::login }


security_logout:
  path:     /logout
  defaults: { _controller: App\Controller\SecurityController::logout }


security_redirectuser:
  path:     /redirectuser
  defaults: { _controller: App\Controller\SecurityController::redirectuser }


security_updpwd:
  path:     /updatepasswd
  defaults: { _controller: App\Controller\SecurityController::updatepwd }


security_updprofil:
  path:     /updateprofil
  defaults: { _controller: App\Controller\SecurityController::updateprofil }


siges_dashboardteacher:
  path:     /teacherarea/dashboardteacher
  defaults: { _controller: App\Controller\TeacherController::dashboardteacher }

siges_averagedashteacher:
  path:     /teacherarea/averagedashteacher
  defaults: { _controller: App\Controller\TeacherController::averagedashteacher }


siges_teachereculist:
  path:     /teacherarea/teachereculist
  defaults: { _controller: App\Controller\TeacherController::teachereculist }


siges_entryaverages:
  path:     /teacherarea/entryaverages
  defaults: { _controller: App\Controller\TeacherController::entryaverages }

